{"name": "test_07", "status": "failed", "statusDetails": {"message": "AssertionError: Error at validation - wrong password\nassert 'No Errors' == 'Epic sadface... this service'\n  - Epic sadface: Username and password do not match any user in this service\n  + No Errors", "trace": "self = <POM.tests.e2e_tests.Test object at 0x0000025840BA8EC0>\n\n    def test_07(self):\n        # Test failed for example\n        p1 = LoginPage(self.driver)\n        error_msg = p1.login(\"standard_user\", \"secret_sauce\")\n>       assert error_msg == \"Epic sadface: Username and password do not match any user in this service\", \"Error at validation - wrong password\"\nE       AssertionError: Error at validation - wrong password\nE       assert 'No Errors' == 'Epic sadface... this service'\nE         - Epic sadface: Username and password do not match any user in this service\nE         + No Errors\n\nPOM\\tests\\e2e_tests.py:82: AssertionError"}, "start": 1725112521022, "stop": 1725112522454, "uuid": "5723659c-36e3-4452-8de7-f2a065d8c63e", "historyId": "cbd99e93324fbaeecbc273ae4474c3d7", "testCaseId": "cbd99e93324fbaeecbc273ae4474c3d7", "fullName": "POM.tests.e2e_tests.Test#test_07", "labels": [{"name": "parentSuite", "value": "POM.tests"}, {"name": "suite", "value": "e2e_tests"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "DESKTOP-0JDPK7J"}, {"name": "thread", "value": "19588-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "POM.tests.e2e_tests"}]}